### ISSUE TITLE
will this work with ASIO plugin?

### ISSUE THREAD

**Issue by THX1082** [lebaston100/MIDItoOBS#22]
question: will this work ASIO plugins for OBS? If it can't be answered, I may just buy a control surface to test myself, but would like to know before purchasing. If it isn't, maybe a feature request?

Here is the [plugin](https://github.com/Andersama/obs-asio)

Thanks!

**Comment by lebaston100** [comment]
ASIO and MIDI are 2 completly different things. ASIO is an audio protocol and midi is a control protocol. MIDItoOBS does not handle ASIO in any way.
If you need more information i suggest you read this first: [https://princetonuniversity.github.io/PUbootcamp/sessions/technical-questions/HowToAskQuestions2018Bootcamp.pdf](https://princetonuniversity.github.io/PUbootcamp/sessions/technical-questions/HowToAskQuestions2018Bootcamp.pdf)

**Comment by lebaston100** [comment]
I will close this for now. Feel free to comment on it again if you have further questions.

**Comment by THX1082** [comment]
I can see how I didn't explain my question very well. I understand ASIO and MIDI are completely different. To expand on my question I will explain a bit. The ASIO plugin adds volume sliders to the mixer that can be completely customized. Say I have a ASIO source with 32 channels, I can just pick the 4 I want and it adds the sliders. I am asking if this plugin can control these sources/sliders from another plugin? Thanks!

**Comment by lebaston100** [comment]
Now your question makes much more sense.
Since in theory the asio plugin only adds another audio source, you should be able to control every slider that is visible in the obs mixer with miditoobs. Just give it a try, run the setup and see if your asio source shows up in the selection list. I have not tested this myself because i don't have a asio interface here right now, but again in theory it should work.
Hope that helps.
