### ISSUE TITLE
Run setup.py on mac: invalid syntax

### ISSUE THREAD

**Issue by donmurdoc** [lebaston100/MIDItoOBS#23]
Hi, tried to run it on macOs.
I got this message:

> $ python setup.py 
  File "setup.py", line 783
    print("Updating \"", old_device_name, "\" to \"", new_device_name, "\" now", sep="")
                                                                                    ^
SyntaxError: invalid syntax

**Comment by lebaston100** [comment]
Interesting. Thanks for the report. I have never tested on mac so it's good to get these errors.
It seems that the \ escapes do not work because the line should read
`print("Updating \"", old_device_name, "\" to \"", new_device_name, "\" now", sep="")`
Do you mind joining the [discord server](https://discord.gg/PCYQJwX) so i can have a better look at it?

**Comment by donmurdoc** [comment]
Wait, i got it, i was using old version of python.
I was running "python setup.py" instead of "python3 setup.py".
So now its working fine setup.py :)

**Comment by lebaston100** [comment]
Hm that would make sense. It's really not designed to be run with python2 for obvious reasons but glad it works now. I will close this issue now, feel free to comment again if you need anything more.
